#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms 2009 v1.0.0.0
# Generated On: 11/11/2008 3:10 PM
# Generated By: bd0794
########################################################################

#region Import the Assembles
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$richTextBox1 = New-Object System.Windows.Forms.RichTextBox
$button1 = New-Object System.Windows.Forms.Button
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$Button1_Click= 
{
$gSlots = psexec \\gremlin "D:\program files\veritas\volmgr\bin\vmquery" -p 4|
	where-object {$_-match "robot slot:"}|
	ForEach-Object {$_-replace "robot ",""}|
	ForEach-Object {$_-replace "            ",""}|
	ForEach-Object {$_-replace "Slot:",""}|
	Foreach-object {$_+"`n"} | Sort-Object
	$l1="          ------------------------------------------------------------------------------------------------------------------------------`n"
	$l2="                              There is/are " + " " + $gSlots.count + " " + "Tape(s) Available in the Scratch Pool`n"
	$l3="          ------------------------------------------------------------------------------------------------------------------------------`n`n"
	$l4="SLOTS`n"
	$l5="------------`n"
    $richTextBox1.Text = $l1 + $l2 + $l3 + $l4 + $l5 + $gSlots 

}

#----------------------------------------------
#region Generated Form Code
$form1.Name = 'form1'
$form1.Text = 'NBU MGMT CONSOLE'
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 589
$System_Drawing_Size.Height = 620
$form1.ClientSize = $System_Drawing_Size

$richTextBox1.Text = ''
$richTextBox1.TabIndex = 1
$richTextBox1.Name = 'richTextBox1'
$richTextBox1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,0,3,0)
$richTextBox1.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$richTextBox1.BorderStyle = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 565
$System_Drawing_Size.Height = 459
$richTextBox1.Size = $System_Drawing_Size
$richTextBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 123
$richTextBox1.Location = $System_Drawing_Point

$form1.Controls.Add($richTextBox1)


$button1.UseVisualStyleBackColor = $True
$button1.Text = 'Sctatch Pool'

$button1.DataBindings.DefaultDataSourceUpdateMode = 0
$button1.TabIndex = 0
$button1.Name = 'button1'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 32
$button1.Size = $System_Drawing_Size
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 12
$button1.Location = $System_Drawing_Point
$button1.add_Click($Button1_Click)

$form1.Controls.Add($button1)

#endregion Generated Form Code

#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
